---
references:
  test_config: &test_config
    working_directory: ~/cli
    environment:
      NYC: "yarn exec nyc -- --nycrc-path node_modules/@oclif/nyc-config/.nycrc"
      MOCHA_FILE: "reports/mocha.xml"
      PERCY_PARALLEL_TOTAL: "-1"

commands:
  setup:
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v2-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
      - run:
          name: Install project dependencies
          command: yarn
      - run:
          name: Install CI only dependencies
          command: yarn add -D --no-lockfile nyc@11 @oclif/nyc-config@1 mocha-junit-reporter@1
      - run:
          name: Build package
          command: yarn build
  unit_client_acceptance_integration:
    steps:
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Unit tests
          command: |
            mkdir -p reports
            $NYC yarn test:unit --reporter mocha-multi --reporter-options spec=-,mocha-junit-reporter=-
      - run:
          name: Client tests
          command: $NYC yarn test:client --singleRun
      - run:
          name: Acceptance tests
          command: echo 'Skipped' # $NYC yarn test:acceptance
      - run:
          name: Integration tests
          command: $NYC yarn test:integration
  cli_integration:
    steps:
      - run:
          name: Snapshot command test
          command: yarn test:command:snapshot
      - run:
          name: Upload command test
          command: yarn test:command:upload
  cli_commands:
    steps:
      - run:
          name: Version command
          command: ./bin/run --version
      - run:
          name: Help command
          command: ./bin/run --help
  store_artifacts:
    steps:
      - run:
          name: Gather reports
          command: $NYC report --reporter text-lcov > coverage.lcov
      - store_test_results: &store_test_results
          path: ~/cli/reports

version: 2.1
jobs:
  node-10:
    <<: *test_config
    docker:
      - image: circleci/node:10-browsers
    steps:
      - setup
      - cli_commands
      - unit_client_acceptance_integration
      - run:
          name: Disable Percy for CLI integration tests
          command: export PERCY_ENABLE=0
      - cli_integration
      - store_artifacts
  node-12:
    <<: *test_config
    docker:
      - image: circleci/node:12-browsers
    steps:
      - setup
      - cli_commands
      - unit_client_acceptance_integration
      - cli_integration
      - store_artifacts
  finalize_percy:
    <<: *test_config
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run: yarn && yarn build
      - run: ./bin/run finalize --all
  release:
    <<: *test_config
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run: yarn
      - run: ./release-percy.sh
workflows:
  version: 2
  default:
    jobs:
      - node-10
      - node-12
      - finalize_percy:
          requires:
          - node-10
          - node-12
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - node-10
            - node-12
