version: "2.1"
description: > 
  Workflow for running Percy builds in parallel. Your token will be read from $PERCY_TOKEN by default, but this
  can be overridden using the `percy_token` parameter. Source Code: https://github.com/percy/percy-agent/

examples:
  finalize_all_percy_builds:
    description: Finalize all Percy builds
    usage:
      version: 2.1

      orbs:
        percy: percy/agent@1.0.0

      workflows:
        percy_finalize_all:
          jobs:
            - percy/finalize_all

executors:
  default:
    docker:
      parameters:
        tag:
          type: string
          description: Docker image tag
          default: "latest"
      docker:
          - image: percyio/agent:<<parameters.tag>>

commands:
  finalize_all:
    description: Finalize all Percy builds
    parameters:
      percy_token:
        description: PERCY_TOKEN for your project. It is found on your project settings.
        type: string
        default: $PERCY_TOKEN
    steps:
      - run: PERCY_TOKEN=<< parameters.percy_token >> percy finalize --all

jobs:
  finalize_all:
    executor: default
    steps:
      - finalize_all
